baseurl: /
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
encoding: utf-8
markdown: rdiscount
name: George
description:  WMYeah
url: http://github.wmyeah.com/
avatar: https://avatars0.githubusercontent.com/u/5527399?v=3&u=00a97d6a93a01f442d675c19e7a393c6222d929f&s=140
