baseurl: /
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
encoding: utf-8
markdown: rdiscount
name: George
description:  No Silver Bullet.
url: http://github.wmyeah.com/
avatar: http://github.wmyeah.com/favicon.ico
